version: '4.3'
services:
  db:
    image: postgres:16.3
    container_name: invest_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432

  chat:
    image: invest_image
    build:
      context: .
    container_name: chat_app
    env_file:
      - .env-non-dev
    depends_on:
      - db
    command: ["chat/docker/app.sh"]
    ports:
      - 8000:3000
